services:
  # RabbitMQ Service
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # Messaging
      - "15672:15672"   # RabbitMQ Management UI
    networks:
      - microservices-network
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 1234

  # PostgreSQL Service
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: baemin_db
    networks:
      - microservices-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Redis Service
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - microservices-network

  # Elasticsearch Service
  elasticsearch:
    image: elasticsearch:7.17.10
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - microservices-network

  # Kibana Service
  kibana:
    image: kibana:7.17.10
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - microservices-network

  # Microservices
  service_product:
    build:
      context: ./service_product
    container_name: service_product
    ports:
      - "3001:3000"
    depends_on:
      - rabbitmq
      - postgres
      - redis
      - elasticsearch
    networks:
      - microservices-network
    environment:
      RABBITMQ_URI: amqp://admin:1234@rabbitmq:5672
      POSTGRES_URI: postgres://postgres:1234@postgres:5432/baemin_db
      REDIS_URI: redis://redis:6379
      ELASTICSEARCH_URI: http://elasticsearch:9200

  service_user:
    build:
      context: ./service_user
    container_name: service_user
    ports:
      - "3002:3000"
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - microservices-network
    environment:
      RABBITMQ_URI: amqp://admin:1234@rabbitmq:5672
      POSTGRES_URI: postgres://postgres:1234@postgres:5432/baemin_db

  service_order:
    build:
      context: ./service_order
    container_name: service_order
    ports:
      - "3003:3000"
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - microservices-network
    environment:
      RABBITMQ_URI: amqp://admin:1234@rabbitmq:5672
      POSTGRES_URI: postgres://postgres:1234@postgres:5432/baemin_db

  service_shipping:
    build:
      context: ./service_shipping
    container_name: service_shipping
    ports:
      - "3004:3000"
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - microservices-network
    environment:
      RABBITMQ_URI: amqp://admin:1234@rabbitmq:5672
      POSTGRES_URI: postgres://postgres:1234@postgres:5432/baemin_db

  # API Gateway Service
  api_gateway:
    build:
      context: ./api_gateway
    container_name: api_gateway
    ports:
      - "3000:3000"
    depends_on:
      - service_product
      - service_user
      - service_order
      - service_shipping
    networks:
      - microservices-network
    environment:
      RABBITMQ_URI: amqp://admin:1234@rabbitmq:5672
      POSTGRES_URI: postgres://postgres:1234@postgres:5432/baemin_db

networks:
  microservices-network:
    driver: bridge

volumes:
  postgres-data:
